# Generated by Django 5.1.1 on 2024-10-16 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yet.profile'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
