# Generated by Django 5.1.1 on 2024-10-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yet', '0002_venue_image_alter_venue_owner_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='venues_images/'),
        ),
        migrations.DeleteModel(
            name='VenueImage',
        ),
    ]
